### ISSUE TITLE
无法查询pss列表，无法生成贴纸

### ISSUE THREAD

**Issue by KnightK22** [Nao-desu/pjsk_sticker#5]
输入“随机1”会报贴纸生成失败‘‘
![image](https://github.com/Nao-desu/pjsk_sticker/assets/57353187/fe4f0081-d563-4529-9aee-2b5fa2616080)

输入’pss列表‘会报一个链接
![image](https://github.com/Nao-desu/pjsk_sticker/assets/57353187/97debf15-4d65-4669-a25f-1696bdb0096c)
![image](https://github.com/Nao-desu/pjsk_sticker/assets/57353187/aa3560fc-95fe-4f34-ad67-21542759ccb8)

请问这个如何解决呢？谢谢大佬

**Comment by PrinceZW96** [comment]
路径和URI 斜杠方向不一样
最简单的办法，init.py 和 pic.py里有几个 filepath用的是 " \ "，把他改成 " / “ 就可以了

**Comment by KnightK22** [comment]
> 路径和URI 斜杠方向不一样 最简单的办法，init.py 和 pic.py里有几个 filepath用的是 " \ "，把他改成 " / “ 就可以了

ok了，谢谢大佬
